stages:
  - build_image
build_image:
  stage: build_image
  image: docker:stable
  variables:
    EXTERNAL_REGISTRY: pdocker.ascs.tech
    BUILD_ARTIFACTS_PATH: .

  script:
    - BUILD_STAMP=$(date -u '+%Y-%m-%d_%I:%M:%S%p')
    - TAG=$(if [ "${CI_COMMIT_REF_NAME}" = "master" ]; then echo latest ; else echo ${CI_COMMIT_REF_NAME} ;fi | sed 's|\/|-|g' )
    - >
      docker build -t ${EXTERNAL_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${TAG} \
        --build-arg gitCommit=${CI_COMMIT_SHA::8} --build-arg buildStamp=${BUILD_STAMP} \
        ${BUILD_ARTIFACTS_PATH}
    - docker push ${EXTERNAL_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:${TAG}
  except:
    - merge_requests
  only:
    - tags
    - master
    - develop
    - /^release\/\d+\.\d+\.\d+$/
